---
build:
    environment:
        php:
            version: 7.4

    services:
        mysql: 5.7

    nodes:
        analysis:

            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - composer self-update
                    - composer install --no-interaction
                    - mysql -e 'CREATE DATABASE beer_test;'
                    - cp .env.travis .env.testing
                    - cp .env.travis .env
                    - php artisan key:generate --env=testing
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
                    - js-scrutinizer-run
        tests:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    # Dont do the test, it doesn't work
                    command: php -v

filter:
    paths:
        - 'app/*'
    excluded_paths:
        - 'app/views/*'
        - 'app/config/*'
        - 'app/database/*'
        - '*.min.js'
checks:
    php: true
    javascript: true

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
