# Inspiration: https://www.fastfwd.com/continuous-integration-laravel-travis-ci/

language: php
php:
  - '7.2'


before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-text
